name: Build VividPM Executables




on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch: # Allow manual triggering
permissions:
  contents: write




jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        include:
          - os: windows-latest
            artifact_name: VividPM_Windows_2.0.0.exe
            asset_name: VividPM_Windows_2.0.0.exe
          - os: macos-latest
            artifact_name: VividPM_macOS_2.0.0.app
            asset_name: VividPM_macOS_2.0.0.zip
          - os: ubuntu-latest
            artifact_name: VividPM_Linux_2.0.0.AppImage
            asset_name: VividPM_Linux_2.0.0.AppImage




    steps:
      - name: Checkout Code
        uses: actions/checkout@v4




      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Use a stable Python version




      - name: Install Dependencies
